#!/usr/bin/env bash
# Changes the following domain resolve IPs:
# - localhost from 127.0.0.1 to 127.0.0.2
# - facebook.com from 157.240.11.35 to 8.8.8.8

sudo tee /etc/hosts >/dev/null <<EOF
127.0.0.2	localhost
8.8.8.8		facebook.com
EOF
